// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8P1aW9pZHx04aSnpdqmGO30S9SfNdcaM',
    appId: '1:171974367468:web:c17b424ebb75cd02ed6dc9',
    messagingSenderId: '171974367468',
    projectId: 'fall-detection-b17ee',
    authDomain: 'fall-detection-b17ee.firebaseapp.com',
    databaseURL: 'https://fall-detection-b17ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-b17ee.firebasestorage.app',
    measurementId: 'G-71ZNZJRN5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGz-xyDTh1PcX5KNISm3m9oqMDYAaJkVo',
    appId: '1:171974367468:android:cddba934bb5311f6ed6dc9',
    messagingSenderId: '171974367468',
    projectId: 'fall-detection-b17ee',
    databaseURL: 'https://fall-detection-b17ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-b17ee.firebasestorage.app',
  );
}
